### ISSUE TITLE
i915 DPST always on

### ISSUE THREAD

**Issue by cjayho** [freebsd/drm-kmod-firmware#18]
Hello.
Got weird and annoying bug with i915 driver: when there is no image refresh, after 1 second screen gets dimmed and colors on screen change. But even mouse move returns screen brightness and normal colors. After stopping mouse move screen after one second dims again.
There is stupid workaround, to show seconds on kde system clock, to let screen repaint every second, but this bug needs to be fixed I think.
In freeBSD 12.2 everything was OK, but not now, in freeBSD 13.0-RC1.
Same bug i experience with new linuxes (with updated GPU firmware, with vanilla 4.16 kernel firmwares, for example, everything is OK).
My hardware: Dell Inspiron 15 3543 (with broadwell-u intel CPU)
Intel display adapters have feature named DPST, and its behavior is the same as i see.

```
pciconf -lv:

vgapci0@pci0:0:2:0:     class=0x030000 rev=0x08 hdr=0x00 vendor=0x8086 device=0x1606 subvendor=0x1028 subdevice=0x0655
    vendor     = 'Intel Corporation'
    device     = 'HD Graphics'
    class      = display
    subclass   = VGA

vgapci1@pci0:8:0:0:     class=0x030200 rev=0xa1 hdr=0x00 vendor=0x10de device=0x1140 subvendor=0x1028 subdevice=0x0655
    vendor     = 'NVIDIA Corporation'
    device     = 'GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]'
    class      = display
    subclass   = 3D
```

**Comment by evadot** [comment]
If there is a bug it's not here, broadwell don't have firmware.
