### ISSUE TITLE
DRM fails to load when firmware is built from source.

### ISSUE THREAD

**Issue by ghost** [freebsd/drm-kmod-firmware#27]
Hello,

when i do install the firmware from source with make install then it fails to load the firmware for NAVI 22.

Using 14-CURRENT with drm 5.16.

May 15 22:34:16 Home kernel: drmn0: could not load firmware image 'amdgpu/navy_flounder_sos.bin'
May 15 22:34:16 Home kernel: drmn0: failed to init sos firmware
May 15 22:34:16 Home kernel: [drm ERROR :psp_sw_init] Failed to load psp firmware!
May 15 22:34:16 Home kernel: [drm ERROR :amdgpu_device_ip_init] sw_init of IP block <psp> failed -2
May 15 22:34:16 Home kernel: drmn0: amdgpu_device_ip_init failed
May 15 22:34:16 Home kernel: drmn0: Fatal error during GPU init
May 15 22:34:16 Home kernel: drmn0: amdgpu: finishing device.
May 15 22:34:16 Home kernel: device_attach: drmn0 attach returned 2

After installing the navy-flounder package with pkg everything went fine.

**Comment by Alexander88207** [comment]
Hmm... looks like its missing, its there a reason for that?

**Comment by Alexander88207** [comment]
I have to set OSVERSION=1400000 even that i am on current already, is this intended?

**Comment by evadot** [comment]
Is it still happening ?

**Comment by evadot** [comment]
Closing as now news.
